const fs = require('fs');
let content = fs.readFileSync('src/components/LiftingToolCertificatesPortfolioView.tsx', 'utf8');

content = content.replace(
  /className="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring\[#683EFF\]\/20 focus:border-\[#683EFF\] bg-slate-50 font-semibold text-slate-700 disabled:opacity-85"\n                      \/>\n                    <\/div>\n\n\n                    <div>\n                      <label className="block text-\[10px\] font-bold text-slate-500 uppercase tracking-widest mb-1\.5">/,
  `className="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#683EFF]/20 focus:border-[#683EFF] bg-slate-50 font-semibold text-slate-700 disabled:opacity-85"\n                      />\n                    </div>\n                    <div>\n                      <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1.5">\n                        Color Code\n                      </label>\n                      <input\n                        type="text"\n                        disabled={!isEditingInDetail}\n                        value={isEditingInDetail && editFormValues ? editFormValues.colorCode || "" : certificate.colorCode || ""}\n                        onChange={(e) => {\n                          if (editFormValues) setEditFormValues({ ...editFormValues, colorCode: e.target.value });\n                        }}\n                        className="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#683EFF]/20 focus:border-[#683EFF] bg-slate-50 font-semibold text-slate-700 disabled:opacity-85"\n                      />\n                    </div>\n\n\n                    <div>\n                      <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1.5">`
);

fs.writeFileSync('src/components/LiftingToolCertificatesPortfolioView.tsx', content);
console.log("Added color code in detail");
